use evdev::KeyCode;

// Every key that Big Picture allows binding.

pub const KEYS: &[Key] = &[
    Key::KeyCode_ESC,
    Key::KeyCode_F1,
    Key::KeyCode_F2,
    Key::KeyCode_F3,
    Key::KeyCode_F4,
    Key::KeyCode_F5,
    Key::KeyCode_F6,
    Key::KeyCode_F7,
    Key::KeyCode_F8,
    Key::KeyCode_F9,
    Key::KeyCode_F10,
    Key::KeyCode_F11,
    Key::KeyCode_F12,

    Key::KeyCode_GRAVE, // `
    Key::KeyCode_1,
    Key::KeyCode_2,
    Key::KeyCode_3,
    Key::KeyCode_4,
    Key::KeyCode_5,
    Key::KeyCode_6,
    Key::KeyCode_7,
    Key::KeyCode_8,
    Key::KeyCode_9,
    Key::KeyCode_0,
    Key::KeyCode_MINUS,
    Key::KeyCode_EQUAL,
    Key::KeyCode_BACKSPACE,

    Key::KeyCode_TAB,
    Key::KeyCode_Q,
    Key::KeyCode_W,
    Key::KeyCode_E,
    Key::KeyCode_R,
    Key::KeyCode_T,
    Key::KeyCode_Y,
    Key::KeyCode_U,
    Key::KeyCode_I,
    Key::KeyCode_O,
    Key::KeyCode_P,
    Key::KeyCode_LEFTBRACE,
    Key::KeyCode_RIGHTBRACE,
    Key::KeyCode_BACKSLASH,

    Key::KeyCode_CAPSLOCK,
    Key::KeyCode_A,
    Key::KeyCode_S,
    Key::KeyCode_D,
    Key::KeyCode_F,
    Key::KeyCode_G,
    Key::KeyCode_H,
    Key::KeyCode_J,
    Key::KeyCode_K,
    Key::KeyCode_L,
    Key::KeyCode_SEMICOLON,
    Key::KeyCode_APOSTROPHE,
    Key::KeyCode_ENTER,

    Key::KeyCode_LEFTSHIFT,
    Key::KeyCode_Z,
    Key::KeyCode_X,
    Key::KeyCode_C,
    Key::KeyCode_V,
    Key::KeyCode_B,
    Key::KeyCode_N,
    Key::KeyCode_M,
    Key::KeyCode_COMMA,
    Key::KeyCode_DOT,
    Key::KeyCode_SLASH,
    Key::KeyCode_RIGHTSHIFT,

    Key::KeyCode_LEFTCTRL,
    Key::KeyCode_RIGHTCTRL,
    Key::KeyCode_LEFTMETA,
    Key::KeyCode_LEFTALT,
    Key::KeyCode_SPACE,
    Key::KeyCode_RIGHTALT,

    Key::KeyCode_VOLUMEUP,
    Key::KeyCode_VOLUMEDOWN,
    Key::KeyCode_MUTE,
    Key::KeyCode_PLAY,
    Key::KeyCode_STOP,
    Key::KeyCode_NEXT,
    Key::KeyCode_PREVIOUS,
    Key::KeyCode_PREVIOUSSONG,
    Key::KeyCode_NEXTSONG,
    Key::KeyCode_PLAYPAUSE,
    Key::KeyCode_INSERT,
    Key::KeyCode_HOME,
    Key::KeyCode_PAGEUP,
    Key::KeyCode_DELETE,
    Key::KeyCode_END,
    Key::KeyCode_PAGEDOWN,

    Key::KeyCode_UP,
    Key::KeyCode_LEFT,
    Key::KeyCode_RIGHT,
    Key::KeyCode_DOWN,

    Key::KeyCode_NUMLOCK,
    Key::KeyCode_KPSLASH,
    Key::KeyCode_KPASTERISK,
    Key::KeyCode_KPMINUS,

    Key::KeyCode_KP7,
    Key::KeyCode_KP8,
    Key::KeyCode_KP9,
    Key::KeyCode_KPPLUS,

    Key::KeyCode_KP4,
    Key::KeyCode_KP5,
    Key::KeyCode_KP6,

    Key::KeyCode_KP1,
    Key::KeyCode_KP2,
    Key::KeyCode_KP3,
    Key::KeyCode_KPENTER,

    Key::KeyCode_KP0,
    Key::KeyCode_KPDOT,
    Key::KeyCode_KPLEFTPAREN,
    Key::KeyCode_KPRIGHTPAREN,
    Key::KeyCode_102ND, // Output by < (less than key)
];
